# NumPy Tutorial
Numpy is the library that gives Python its ability to work with data at speed. Originally, launched in 1995 as 'Numeric,' NumPy is the foundation on which many important Python data science libraries are built, including Pandas, SciPy and scikit-learn. Let us get started with using and learning Numpy.

Here is a Good Reference URL to playaroud 
https://www.dataquest.io/blog/numpy-cheat-sheet/

In [3]:
import numpy as np

In [4]:
np.loadtxt('file.txt') ##| From a text file

array([  2.,  33.,   4.,  25.,   6.,   7.])

In [5]:

np.genfromtxt('file.csv',delimiter=',') # | From a CSV file

/home/rbhupathi/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: UserWarning: genfromtxt: Empty input file: "file.csv"
  


array([], dtype=float64)

In [6]:
arr= np.array([2,33,4,25,6,7])
np.savetxt('file.txt',arr,delimiter=' ')# | Writes to a text file

In [7]:
np.array([1,2,3]) ## One dimensional array

np.random.randint(5,size=(2,3)) #| 2x3 array with random ints between 0-4



array([[4, 2, 2],
       [0, 1, 0]])

In [8]:
np.array([(1,2,3),(4,5,6)]) #| Two dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.zeros(3) #| 1D array of length 3 all values 0

array([ 0.,  0.,  0.])

In [10]:
np.ones((3,4)) #| 3x4 array with all values 1

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [11]:
np.eye(5) #| 5x5 array of 0 with 1 on diagonal (Identity matrix)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [12]:
np.linspace(0,100,6) #| Array of 6 evenly divided values from 0 to 100

array([   0.,   20.,   40.,   60.,   80.,  100.])

In [13]:
np.arange(0,10,3) #| Array of values from 0 to less than 10 with step 3 (eg [0,3,6,9])

array([0, 3, 6, 9])

In [14]:
np.full((2,3),8) #| 2x3 array with all values 8

array([[8, 8, 8],
       [8, 8, 8]])

In [15]:
np.random.rand(4,5) #| 4x5 array of random floats between 0-1

array([[ 0.66322544,  0.41331352,  0.15244125,  0.29206797,  0.09777   ],
       [ 0.51513673,  0.94518736,  0.25058522,  0.79578952,  0.08661794],
       [ 0.39607845,  0.42108643,  0.8207859 ,  0.48716579,  0.04270515],
       [ 0.58389713,  0.85721158,  0.12839073,  0.31420433,  0.34785702]])

In [16]:
np.random.rand(6,8)*100 #|# 6x7 array of random floats between 0-100

array([[ 74.38102792,  37.07786637,  65.96976184,   2.76965926,
         37.38370521,  14.85868297,   9.81291024,  86.66882889],
       [ 21.62253806,  36.00493665,  22.68066514,  62.50179492,
         48.35121915,  21.88470193,  19.10052314,  47.41376186],
       [ 56.18240909,  18.88333376,  74.01739821,  15.4778479 ,
          2.40687456,  53.64380681,  78.88505917,  90.92555383],
       [ 81.28913132,  45.36478843,  41.35195522,  59.24097479,
         33.69771937,  38.39630807,  31.99650873,  33.69637953],
       [ 78.8997691 ,  59.39551121,  39.12396999,  93.20642244,
         60.02337683,  18.47778879,  23.18064445,   9.79225336],
       [  5.47773634,  38.45413622,  24.92984062,  16.71623836,
         17.79557184,  83.82498599,  69.42653201,  36.69248657]])

In [17]:
np.random.random(6)*100 # 

array([ 11.88614613,  21.09169472,  43.98293097,  89.20942508,
        25.02798469,  19.52401675])

# Inspecting Numpy Properties

In [18]:
arr= np.random.rand(7,8)
arr.size #| Returns number of elements in arr


56

In [19]:
arr.shape #| Returns dimensions of arr (rows,columns)

(7, 8)

In [20]:
arr.reshape(8,7) #| Reshapes arr to 3 rows, 4 columns without changing data


array([[ 0.21334561,  0.73271105,  0.49678053,  0.77114822,  0.36103517,
         0.92927208,  0.73117026],
       [ 0.38813793,  0.41771781,  0.74249584,  0.80481757,  0.53719581,
         0.46397436,  0.88582339],
       [ 0.53883991,  0.41843365,  0.65150896,  0.42714875,  0.95508636,
         0.05221604,  0.81000672],
       [ 0.14206148,  0.05900495,  0.56495802,  0.71858764,  0.13044406,
         0.01558475,  0.52916105],
       [ 0.09437895,  0.29040601,  0.14993367,  0.96230284,  0.24575605,
         0.70017014,  0.80862508],
       [ 0.02749607,  0.84613089,  0.22600285,  0.73421987,  0.45838803,
         0.23313285,  0.04318389],
       [ 0.8073859 ,  0.16618066,  0.29141479,  0.74703399,  0.62229083,
         0.12747999,  0.28073162],
       [ 0.69845887,  0.72057707,  0.89881551,  0.79709691,  0.92874576,
         0.33357671,  0.07222425]])

In [21]:
arr.resize(7,8) #| Changes arr shape to 5x6 and fills new values with 0

In [22]:
arr

array([[ 0.21334561,  0.73271105,  0.49678053,  0.77114822,  0.36103517,
         0.92927208,  0.73117026,  0.38813793],
       [ 0.41771781,  0.74249584,  0.80481757,  0.53719581,  0.46397436,
         0.88582339,  0.53883991,  0.41843365],
       [ 0.65150896,  0.42714875,  0.95508636,  0.05221604,  0.81000672,
         0.14206148,  0.05900495,  0.56495802],
       [ 0.71858764,  0.13044406,  0.01558475,  0.52916105,  0.09437895,
         0.29040601,  0.14993367,  0.96230284],
       [ 0.24575605,  0.70017014,  0.80862508,  0.02749607,  0.84613089,
         0.22600285,  0.73421987,  0.45838803],
       [ 0.23313285,  0.04318389,  0.8073859 ,  0.16618066,  0.29141479,
         0.74703399,  0.62229083,  0.12747999],
       [ 0.28073162,  0.69845887,  0.72057707,  0.89881551,  0.79709691,
         0.92874576,  0.33357671,  0.07222425]])

In [23]:
np.resize(arr,(10,10))  #If the new array is larger than the original array, 
#then the new array is filled with repeated copies of a. Note that this behavior 
#is different from a.resize(new_shape) which fills with zeros instead of repeated copies of a.

array([[ 0.21334561,  0.73271105,  0.49678053,  0.77114822,  0.36103517,
         0.92927208,  0.73117026,  0.38813793,  0.41771781,  0.74249584],
       [ 0.80481757,  0.53719581,  0.46397436,  0.88582339,  0.53883991,
         0.41843365,  0.65150896,  0.42714875,  0.95508636,  0.05221604],
       [ 0.81000672,  0.14206148,  0.05900495,  0.56495802,  0.71858764,
         0.13044406,  0.01558475,  0.52916105,  0.09437895,  0.29040601],
       [ 0.14993367,  0.96230284,  0.24575605,  0.70017014,  0.80862508,
         0.02749607,  0.84613089,  0.22600285,  0.73421987,  0.45838803],
       [ 0.23313285,  0.04318389,  0.8073859 ,  0.16618066,  0.29141479,
         0.74703399,  0.62229083,  0.12747999,  0.28073162,  0.69845887],
       [ 0.72057707,  0.89881551,  0.79709691,  0.92874576,  0.33357671,
         0.07222425,  0.21334561,  0.73271105,  0.49678053,  0.77114822],
       [ 0.36103517,  0.92927208,  0.73117026,  0.38813793,  0.41771781,
         0.74249584,  0.80481757,  0.53719581

In [24]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))  ## Resizes the array , filling the missing values with zeros

array([[0, 1, 2],
       [3, 0, 1]])

In [25]:
multi_dim=np.random.rand(4,5,6) * 10  #creating a 3 dimensioan array . The shape parameter is very important

In [34]:
multi_dim


array([[[ 6.71057844,  5.95530392,  4.04871573,  9.86134054,  2.40111807,
          8.08563255],
        [ 4.25393049,  7.23536507,  7.86757994,  4.09216314,  4.68660577,
          2.86024634],
        [ 2.46957737,  8.21833753,  5.71581885,  4.12148194,  5.47500659,
          3.08459758],
        [ 0.66052484,  7.7593569 ,  5.05006223,  7.50389051,  5.69145356,
          5.95445413],
        [ 7.31043698,  0.5589532 ,  8.00197824,  9.88839935,  6.99868961,
          5.29683189]],

       [[ 9.39008505,  9.15439529,  9.93972738,  2.91640001,  9.00501639,
          2.78030383],
        [ 1.56241519,  6.87172808,  6.15803021,  5.18539644,  9.57200746,
          3.05891898],
        [ 4.24816387,  3.31632394,  1.9090437 ,  6.75039788,  2.29086635,
          9.61571457],
        [ 3.60663901,  3.34624598,  9.59332172,  3.1212261 ,  0.56344686,
          3.92110407],
        [ 6.49464563,  0.57880235,  1.80907198,  1.16262148,  9.3106623 ,
          9.46985769]],

       [[ 0.2265064 ,  7.9

# Accessing and slicing array elements ... HOMEWORK . Use the URL at the top of this page 

In [35]:
 multi_dim[2,3,4]
        

9.8239368222849137

Copyright © 2018 Bhupathi Consulting Inc.